# Generated by Django 3.2.15 on 2022-11-21 14:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmresult",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("SUCCESS", "Status Success"), ("FAILURE", "Status Failure")],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
