variables:
    # Change pip's cache directory to be inside the project directory since we can
    # only cache local items.
    PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'

stages:
    - test
    - build
    - deploy

#
# The tasks.
#

# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
- template: Security/SAST.gitlab-ci.yml

pre-commit:
    stage: test
    needs: []
    image: carboncoop/python-plus-node:3.8-and-14.16
    variables:
        PIP_CACHE_DIR: '${CI_PROJECT_DIR}/.cache/pip'
        PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
    cache:
        key: pre-commit
        when: 'always'
        paths:
            - ${PIP_CACHE_DIR}
            - ${PRE_COMMIT_HOME}
            - node_modules

    before_script:
        - npm install
    script:
        - python -V
        - pip install pre-commit==2.13.0
        - pre-commit run --all

pages:
    stage: deploy
    needs: []
    image: python:3.8
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
          changes:
          - docs/**/*

    artifacts:
        paths:
            - public

    script:
        - pip install -r requirements/docs.txt
        - make clean -C docs/
        - make html -C docs/
        - mv docs/_build/html/ public/
