repos:
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args:
      - --line-length=88

- repo: https://github.com/PyCQA/flake8 
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: [
      'flake8-docstrings==1.5.0',
    ]

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.0.1
  hooks:
  - id: reorder-python-imports

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.4.1
  hooks:
    - id: prettier
      files: "\\.(\
          css|scss\
          |js\
          )$"

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.2.0
  hooks:
  - id: eslint
    exclude: |
      (?x)^(
        prospector/static/js/main.js|
        webpack.config.js
      )$
    additional_dependencies:
    - eslint@7.15.0
    - eslint-plugin-compat@3.8.0
    - eslint-config-prettier@7.0.0

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-merge-conflict
  - id: debug-statements

- repo: https://github.com/rtts/djhtml
  rev: v1.4.10
  hooks:
    - id: djhtml
