# Generated by Django 3.2.15 on 2023-09-08 17:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("parity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paritydata",
            name="type",
            field=models.CharField(max_length=30),
        ),
    ]
