# Generated by Django 3.2.15 on 2023-09-08 17:30
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("parity", "0002_alter_paritydata_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paritydata",
            name="attachment",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="controls_adequacy",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="floor_construction",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="floor_insulation",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="glazing",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="heating",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="local_authority",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="main_fuel",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="parliamentary_constituency",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="region_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="roof_construction",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="roof_insulation",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="tenure",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="type",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="wall_construction",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="wall_insulation",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="ward",
            field=models.CharField(max_length=128),
        ),
    ]
