# Generated by Django 3.2.15 on 2023-09-08 17:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("parity", "0003_auto_20230908_1830"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paritydata",
            name="org_ref",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="paritydata",
            name="uprn",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
