# Generated by Django 3.2.15 on 2023-11-05 19:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("parity", "0004_auto_20230908_1854"),
    ]

    operations = [
        migrations.AddField(
            model_name="paritydata",
            name="multiple_deprivation_index",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
