# Generated by Django 3.2.15 on 2024-01-24 15:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("parity", "0005_paritydata_multiple_deprivation_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="paritydata",
            name="tax_band",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
