version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  postgres:
    image: postgis/postgis:12-2.5-alpine
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    environment:
        POSTGRES_USER: prospector
        POSTGRES_PASSWORD: barge-coheir-beguile-handgun
        POSTGRES_DB: prospector
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    image: redis:5
    ports:
      - "6379:6379"
