# Generated by Django 4.0.1 on 2022-01-27 10:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0001_initial_minimal_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="address_1",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="answers",
            name="address_2",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="answers",
            name="address_3",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="answers",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="answers",
            name="contact_preference",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="answers",
            name="email",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="answers",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="is_occupant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answers",
            name="last_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="Last name"),
        ),
        migrations.AddField(
            model_name="answers",
            name="occupant_first_name",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Occupant first name"
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="occupant_last_name",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Occupant last name"
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="postcode",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="answers",
            name="property_address_1",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="answers",
            name="property_address_2",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="answers",
            name="property_address_3",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="answers",
            name="property_ownership",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OWNED", "Property is in private ownership"),
                    ("RENTAL", "Property is rented from a private landlord"),
                    (
                        "SOCIAL",
                        "Property is rented from a social landlord or local authority",
                    ),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="property_postcode",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
