# Generated by Django 4.0.1 on 2022-01-31 17:30
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0003_add_relationship_data_source_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentGranted",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consent",
                    models.CharField(
                        choices=[
                            ("CALLBACK", "To call/email you back to provide advice"),
                            (
                                "RETAIN",
                                "To hold your details on file and contact you when we think there are schemes that are relevant for you",
                            ),
                            (
                                "ASSESS",
                                "To use the details you have provided to assess eligibility for current schemes",
                            ),
                            (
                                "REPORTING",
                                "To use in anonymised reporting that relates to the energy efficiency of properties in the Plymouth City Council administrative area",
                            ),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "granted_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionnaire.answers",
                    ),
                ),
            ],
        ),
    ]
