# Generated by Django 4.0.1 on 2022-02-02 10:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0004_add_consents_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="property_udprn",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Property UDPRN from API"
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="udprn",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Respondent UDPRN from API"
            ),
        ),
    ]
