# Generated by Django 4.0.1 on 2022-02-03 14:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0005_add_udrpn_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="contact_preference",
        ),
        migrations.AddField(
            model_name="answers",
            name="contact_mobile",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="answers",
            name="property_age_band",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "Before 1900"),
                    (1900, "1900-1929"),
                    (1930, "1930-1949"),
                    (1950, "1950-1966"),
                    (1967, "1967-1975"),
                    (1976, "1976-1990"),
                    (1991, "1991-2002"),
                    (2003, "Since 2003"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="property_age_band_orig",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "Before 1900"),
                    (1900, "1900-1929"),
                    (1930, "1930-1949"),
                    (1950, "1950-1966"),
                    (1967, "1967-1975"),
                    (1976, "1976-1990"),
                    (1991, "1991-2002"),
                    (2003, "Since 2003"),
                ],
                max_length=12,
                verbose_name="Property age band according to property data source before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="property_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DETACHED", "Detached"),
                    ("SEMI", "Semi-detached"),
                    ("MID_TERRACE", "Mid-terrace"),
                    ("END_TERRACE", "End-terrace"),
                    ("MAISONNETTE", "Maisonette"),
                    (
                        "FLAT_CONVERSION",
                        "Flat (converted house or block of 5 or less flats)",
                    ),
                    (
                        "FLAT_BLOCK",
                        "Flat (block of 5 or more flats or flat in mixed use building)",
                    ),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="property_form_orig",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DETACHED", "Detached"),
                    ("SEMI", "Semi-detached"),
                    ("MID_TERRACE", "Mid-terrace"),
                    ("END_TERRACE", "End-terrace"),
                    ("MAISONNETTE", "Maisonette"),
                    (
                        "FLAT_CONVERSION",
                        "Flat (converted house or block of 5 or less flats)",
                    ),
                    (
                        "FLAT_BLOCK",
                        "Flat (block of 5 or more flats or flat in mixed use building)",
                    ),
                ],
                max_length=15,
                verbose_name="Property form according to property data source before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FLAT", "Flat or maisonette"),
                    ("HOUSE", "House"),
                    ("BUNGALOW", "Bungalow"),
                    ("PARK_HOME", "Park Home"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="property_type_orig",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FLAT", "Flat or maisonette"),
                    ("HOUSE", "House"),
                    ("BUNGALOW", "Bungalow"),
                    ("PARK_HOME", "Park Home"),
                ],
                max_length=10,
                verbose_name="Property type according to property data source before correction",
            ),
        ),
    ]
