# Generated by Django 4.0.1 on 2022-02-07 16:06
from django.db import migrations
from django.db import models


def blank_to_null(apps, schema_editor):
    Answers = apps.get_model("questionnaire", "Answers")
    for obj in Answers.objects.all():
        if obj.property_age_band == "":
            obj.property_age_band = None
        if obj.property_age_band_orig == "":
            obj.property_age_band_orig = None
        obj.save()


def null_to_blank(apps, schema_editor):
    Answers = apps.get_model("questionnaire", "Answers")
    for obj in Answers.objects.all():
        if obj.property_age_band is None:
            obj.property_age_band = ""
        if obj.property_age_band_orig is None:
            obj.property_age_band_orig = ""
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0006_add_property_type_age_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="property_age_band",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "Before 1900"),
                    (1900, "1900-1929"),
                    (1930, "1930-1949"),
                    (1950, "1950-1966"),
                    (1967, "1967-1975"),
                    (1976, "1976-1990"),
                    (1991, "1991-2002"),
                    (2003, "Since 2003"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="property_age_band_orig",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "Before 1900"),
                    (1900, "1900-1929"),
                    (1930, "1930-1949"),
                    (1950, "1950-1966"),
                    (1967, "1967-1975"),
                    (1976, "1976-1990"),
                    (1991, "1991-2002"),
                    (2003, "Since 2003"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.RunPython(blank_to_null, null_to_blank),
        migrations.AddField(
            model_name="answers",
            name="ch_timer",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a heating timer control",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="ch_timer_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a heating timer control according to property data before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="flat_roof",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Main part of property has a flat roof",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="flat_roof_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Main part of property has a flat roof, according to property data source before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="gas_boiler_present",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a gas central heating boiler",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="gas_boiler_present_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a gas central heating boiler according to property data before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="hwt_present",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Property has a hot water tank"
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="programmable_thermostat",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a programmable thermostat control",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="programmable_thermostat_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a programmable thermostat control according to property data before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="rir_insulated",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Room-in-roof is insulated"
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="rir_insulated_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Room-in-roof is insulated, according to property data source before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="roof_space_insulated",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Roof space is insulated"
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="roof_space_insulated_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Roof space is insulated, according to property data source before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="room_in_roof",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a room in the roof space",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="room_in_roof_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a room in the roof space, according to property data source before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="room_thermostat",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Property has a room thermostat"
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="room_thermostat_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a room thermostat according to property data before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="smart_thermostat",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a programmable thermostat control",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="suspended_floor",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a suspended timber floor",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="suspended_floor_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a suspended timber floor, according to property data source before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="trvs_present",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has themostatic radiator valves",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="trvs_present_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has thermostatic radiator valves according to property data before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="unheated_loft",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has an unheated loft space with exposed rafters and joists",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="unheated_loft_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has an unheated loft space, according to property data source before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="wall_type",
            field=models.CharField(
                blank=True,
                choices=[("SOLID", "Solid walls"), ("CAVITY", "Cavity walls")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="wall_type_orig",
            field=models.CharField(
                blank=True,
                choices=[("SOLID", "Solid walls"), ("CAVITY", "Cavity walls")],
                max_length=10,
                verbose_name="Wall type according to property data source before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="walls_insulated",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Walls are predominantly insulated"
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="walls_insulated_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Walls are predominantly insulated, according to property data source before correction",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="property_age_band",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Before 1900"),
                    (1900, "1900-1929"),
                    (1930, "1930-1949"),
                    (1950, "1950-1966"),
                    (1967, "1967-1975"),
                    (1976, "1976-1990"),
                    (1991, "1991-2002"),
                    (2003, "Since 2003"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="property_age_band_orig",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Before 1900"),
                    (1900, "1900-1929"),
                    (1930, "1930-1949"),
                    (1950, "1950-1966"),
                    (1967, "1967-1975"),
                    (1976, "1976-1990"),
                    (1991, "1991-2002"),
                    (2003, "Since 2003"),
                ],
                null=True,
                verbose_name="Property age band according to property data source before correction",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="property_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DETACHED", "Detached"),
                    ("SEMI_DETACHED", "Semi-detached"),
                    ("MID_TERRACE", "Mid-terrace"),
                    ("END_TERRACE", "End-terrace"),
                    ("MAISONNETTE", "Maisonette"),
                    (
                        "FLAT_CONVERSION",
                        "Flat (converted house or block of 5 or less flats)",
                    ),
                    (
                        "FLAT_BLOCK",
                        "Flat (block of 5 or more flats or flat in mixed use building)",
                    ),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="property_form_orig",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DETACHED", "Detached"),
                    ("SEMI_DETACHED", "Semi-detached"),
                    ("MID_TERRACE", "Mid-terrace"),
                    ("END_TERRACE", "End-terrace"),
                    ("MAISONNETTE", "Maisonette"),
                    (
                        "FLAT_CONVERSION",
                        "Flat (converted house or block of 5 or less flats)",
                    ),
                    (
                        "FLAT_BLOCK",
                        "Flat (block of 5 or more flats or flat in mixed use building)",
                    ),
                ],
                max_length=15,
                verbose_name="Property form according to property data source before correction",
            ),
        ),
    ]
