# Generated by Django 4.0.1 on 2022-02-08 10:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0007_add_remaining_energy_fields_fix_integerchoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="flat_roof_modern",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="The property's flat roof was build or insulated after 1980",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="gas_boiler_age",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BEFORE_2004", "Before 2004"),
                    ("2004-2014", "Between 2004 and 2014 (inclusive)"),
                    ("2015-2017", "Between 2015 and 2017 (inclusive)"),
                    ("AFTER_2018", "Since 2018"),
                ],
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="gas_boiler_broken",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property's mains gas central heating boiler is currently not working",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="hhrshs_present",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has high heat retention storage heaters",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="other_heating_fuel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OIL", "Oil"),
                    ("LPG", "LPG"),
                    ("COAL", "Coal"),
                    ("WOOD", "Wood"),
                    ("ELECTRIC", "Electricity"),
                    ("DISTRICT", "Shared/district heating network"),
                ],
                max_length=11,
                verbose_name="Non-gas central heating fuel used in property",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="other_heating_fuel_orig",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OIL", "Oil"),
                    ("LPG", "LPG"),
                    ("COAL", "Coal"),
                    ("WOOD", "Wood"),
                    ("ELECTRIC", "Electricity"),
                    ("DISTRICT", "Shared/district heating network"),
                ],
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="other_heating_present",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a non-gas-powered central heating system",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="other_heating_present_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has non-gas-powered central heating according to property data before correction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="storage_heaters_present",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has electric storage heaters",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="storage_heaters_present_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has electric storage heaters according to property data before correction",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="gas_boiler_present",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a mains gas central heating boiler",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="gas_boiler_present_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a mains gas central heating boiler according to property data before correction",
            ),
        ),
    ]
