# Generated by Django 4.0.1 on 2022-02-08 16:36
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0009_add_constraint_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="suspended_floor_insulated",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has an insulated suspended timber floor",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="suspended_floor_insulated_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has an insulated suspended floor, according to property data source before correction",
            ),
        ),
    ]
