# Generated by Django 4.0.1 on 2022-02-09 15:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0010_suspended_floor_insulated_missed_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="sap_rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
