# Generated by Django 4.0.1 on 2022-02-23 17:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0011_add_SAP_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answers",
            options={"verbose_name_plural": "answers"},
        ),
        migrations.AddField(
            model_name="answers",
            name="heat_pump_present",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Property has a heat pump"
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="heat_pump_present_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has a heat pump, according to property data before correction",
            ),
        ),
    ]
