# Generated by Django 4.0.1 on 2022-02-24 17:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0013_remove_consents"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="on_mains_gas",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property is connected to the mains gas network",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="on_mains_gas_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property is connected to the mains gas network according to property data before correction",
            ),
        ),
    ]
