# Generated by Django 4.0.1 on 2022-02-28 13:33
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0014_add_mains_gas_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="electric_radiators_present",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has instantaneous electric heaters",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="electric_radiators_present_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has instantaneous electric heaters according to property data before correction",
            ),
        ),
    ]
