# Generated by Django 4.0.1 on 2022-02-28 14:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0015_add_electric_radiators_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="flat_roof_modern",
        ),
        migrations.AddField(
            model_name="answers",
            name="flat_roof_insulated",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEFINITELY", "Yes definitely"),
                    ("PROBABLY", "Yes I think so"),
                    ("PROBABLY_NOT", "I think not"),
                    ("DEFINITELY_NOT", "I know it isn't"),
                    ("UNKNOWN", "I don't know"),
                ],
                max_length=14,
                verbose_name="The property's flat roof is well insulated",
            ),
        ),
    ]
