# Generated by Django 4.0.1 on 2022-02-28 16:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0016_flat_roof_insulated_not_modern"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answers",
            old_name="respondent_relationship_other",
            new_name="respondent_role_other",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="is_occupant",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="respondent_relationship",
        ),
        migrations.AddField(
            model_name="answers",
            name="respondent_role",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "RESIDENT_HOUSEHOLDER",
                        "I am the householder and live in the property",
                    ),
                    (
                        "NON_RESIDENT_HOUSEHOLDER",
                        "I am the householder but not resident in the property",
                    ),
                    ("OCCUPANT", "I live in the property but am not the householder"),
                    ("FRIEND", "I am a non-resident friend of the householder"),
                    ("PARENT", "I am a non-resident parent of the householder"),
                    ("CHILD", "I am a non-resident child of the householder"),
                    ("FAMILY", "I am another relative of the householder"),
                    ("OTHER", "Other"),
                ],
                max_length=24,
                verbose_name="Relationship of respondent to property",
            ),
        ),
    ]
