# Generated by Django 4.0.1 on 2022-02-28 16:42
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0017_single_respondent_role_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answers",
            old_name="address_1",
            new_name="respondent_address_1",
        ),
        migrations.RenameField(
            model_name="answers",
            old_name="address_2",
            new_name="respondent_address_2",
        ),
        migrations.RenameField(
            model_name="answers",
            old_name="address_3",
            new_name="respondent_address_3",
        ),
        migrations.RenameField(
            model_name="answers",
            old_name="postcode",
            new_name="respondent_postcode",
        ),
        migrations.RenameField(
            model_name="answers",
            old_name="udprn",
            new_name="respondent_udprn",
        ),
    ]
