# Generated by Django 4.0.1 on 2022-03-01 17:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0018_clarify_respondent_address_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="motivation_unknown",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Respondent cannot give motivations of the homeowner",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="tolerated_disruption",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "UP_TO_ONE_DAY",
                        "Jobs that take up to three hours inside home, up to one day outside home",
                    ),
                    (
                        "ONE_TO_FOUR_DAYS",
                        "One or two days of work inside home, or three to four days taking place on exterior to property (involving scaffolding etc.)",
                    ),
                    (
                        "THREE_TO_TEN_DAYS",
                        "Up to five days of work inside home, up to ten days outside the home",
                    ),
                    (
                        "TWO_WEEKS_TO_A_MONTH",
                        "Up to two weeks of work inside home, up to one month outside the home",
                    ),
                    ("UNKNOWN", "I don't know."),
                ],
                max_length=20,
                verbose_name="Maximum length of disruption tolerated",
            ),
        ),
    ]
