# Generated by Django 4.0.1 on 2022-03-01 18:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0019_add_non_householder_options_for_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="contribution_capacity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "No"),
                    ("UP_TO_500", "Yes - up to £500"),
                    ("UP_TO_5K", "Yes - up to £5,000"),
                    ("UP_TO_10K", "Yes - up to £10,000"),
                    ("OVER_10K", "Yes - more than £10,000"),
                    ("UNKNOWN", "I don't know"),
                ],
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="state_of_repair",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "EXCELLENT",
                        "Excellent – recently renovated and all walls, roofs, windows, doors and ventilation in good condition.",
                    ),
                    (
                        "GOOD",
                        "Good – there are no known issues with the house and I have ventilation in the kitchen and bathrooms.",
                    ),
                    (
                        "AVERAGE",
                        "Average  - there are no known issues with the house but I don’t know if I have enough ventilation and I don’t know what condition the external elements (such as roofs, walls and windows) are in.",
                    ),
                    (
                        "POOR",
                        "Poor – There are known issues with the property such as damp or leaks and/or there is no formal ventilation.",
                    ),
                    ("UNKNOWN", "I don't know the state of repair of the property."),
                ],
                max_length=9,
            ),
        ),
    ]
