# Generated by Django 4.0.1 on 2022-03-02 14:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0020_add_more_householder_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="adults",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4 or more")],
                null=True,
                verbose_name="Number of adults living in the property",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="child_benefit",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Anyone in the house is receiving child benefit",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="child_benefit_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Relevant income threshold for child benefit recipient(s)",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="children",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "None"), (1, "1"), (2, "2"), (3, "3"), (4, "4 or more")],
                null=True,
                verbose_name="Number of children living in the property",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="disability_benefits",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Anyone in the house is receiving any disability related benefit",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="income_lt_child_benefit_threshold",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Total household income is under the relevant child benefit threshold",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="take_home_lt_30k",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "Yes, it's under that figure"),
                    ("NO", "No, it's over that figure"),
                    ("MAYBE", "It's close to that figure, could be just over or under"),
                    ("UNKNOWN", "I don't know"),
                ],
                max_length=7,
                verbose_name="Total household take home pay is under £30,000 pa",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="total_income_lt_30k",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "Yes, it's under that figure"),
                    ("NO", "No, it's over that figure"),
                    ("MAYBE", "It's close to that figure, could be just over or under"),
                    ("UNKNOWN", "I don't know"),
                ],
                max_length=7,
                verbose_name="Total gross household income is under £30,000 pa",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="vulnerable_age",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Anyone in the house is vulnerable due to being aged over 65",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="vulnerable_cariovascular",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Anyone in the house is vulnerable due to a cardiovascual condition",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="vulnerable_child_pregnancy",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Anyone in the house is under five years old or pregnant",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="vulnerable_cns",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Anyone in the house is vulnerable due to central nervous system condition",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="vulnerable_disability",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Anyone in the house is vulnerable due to disability",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="vulnerable_mental_health",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Anyone in the house is vulnerable due to a mental health condition",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="vulnerable_respiratory",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Anyone in the house is vulnerable due to a respiratory condition",
            ),
        ),
    ]
