# Generated by Django 4.0.1 on 2022-03-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0021_add_household_income_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='will_correct_floor',
            field=models.BooleanField(blank=True, null=True, verbose_name='Respondent chose to correct floor characteristics'),
        ),
        migrations.AddField(
            model_name='answers',
            name='will_correct_heating',
            field=models.BooleanField(blank=True, null=True, verbose_name='Respondent chose to correct heating system fields'),
        ),
        migrations.AddField(
            model_name='answers',
            name='will_correct_roof',
            field=models.BooleanField(blank=True, null=True, verbose_name='Respondent chose to correct roof characteristics'),
        ),
        migrations.AddField(
            model_name='answers',
            name='will_correct_type',
            field=models.BooleanField(blank=True, null=True, verbose_name='Respondent chose to correct property type or age fields'),
        ),
        migrations.AddField(
            model_name='answers',
            name='will_correct_walls',
            field=models.BooleanField(blank=True, null=True, verbose_name='Respondent chose to correct walls characteristics'),
        ),
    ]
