# Generated by Django 4.0.1 on 2022-03-03 11:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0022_add_will_correct_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="hhrshs_present_orig",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Property has high heat retention storage heaters according to property data before correction",
            ),
        ),
    ]
