# Generated by Django 4.0.1 on 2022-03-03 18:04
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0023_add_hhrshs_inferral"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseholdAdult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adult_number", models.PositiveSmallIntegerField()),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="First name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Last name"
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EMPLOYED", "Employed"),
                            ("SELF_EMPLOYED", "Self Employed"),
                            ("UNEMPLOYED", "Unemployed"),
                            ("RETIRED", "Retired"),
                            ("OTHER", "Other"),
                        ],
                        max_length=13,
                    ),
                ),
                ("employed_income", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "employed_income_frequency",
                    models.CharField(
                        blank=True,
                        choices=[("ANNUALLY", "annually"), ("MONTHLY", "monthly")],
                        max_length=8,
                    ),
                ),
                (
                    "self_employed_income",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "self_employed_income_frequency",
                    models.CharField(
                        blank=True,
                        choices=[("ANNUALLY", "annually"), ("MONTHLY", "monthly")],
                        max_length=8,
                    ),
                ),
                ("business_income", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "business_income_frequency",
                    models.CharField(
                        blank=True,
                        choices=[("ANNUALLY", "annually"), ("MONTHLY", "monthly")],
                        max_length=8,
                    ),
                ),
                (
                    "private_pension_income",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "private_pension_income_frequency",
                    models.CharField(
                        blank=True,
                        choices=[("ANNUALLY", "annually"), ("MONTHLY", "monthly")],
                        max_length=8,
                    ),
                ),
                (
                    "state_pension_income",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "state_pension_income_frequency",
                    models.CharField(
                        blank=True,
                        choices=[("ANNUALLY", "annually"), ("MONTHLY", "monthly")],
                        max_length=8,
                    ),
                ),
                (
                    "saving_investment_income",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "saving_investment_income_frequency",
                    models.CharField(
                        blank=True,
                        choices=[("ANNUALLY", "annually"), ("MONTHLY", "monthly")],
                        max_length=8,
                    ),
                ),
                (
                    "answers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionnaire.answers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WelfareBenefit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("UC", "Universal Credit"),
                            ("JSA", "Job Seekers Allowance (JSA)"),
                            ("ESA", "Employment and Support Allowance (ESA)"),
                            ("INCOME_SUPPORT", "Income Support"),
                            ("CHILD_TAX_CREDIT", "Child Tax Credit"),
                            ("WORKING_TAX_CREDIT", "Working Tax Credit"),
                            ("CHILD_BENEFIT", "Child Benefit"),
                            ("HOUSING_BENEFIT", "Housing Benefit"),
                            ("ATTENDANCE_ALLOWANCE", "Attendance Allowance"),
                            ("CARERS_ALLOWANCE", "Carers Allowance"),
                            ("DLA", "Disability Living Allowance (DLA)"),
                            ("PIP", "Personal Independence Payment (PIP)"),
                            ("PENSION_CREDIT", "Pension Credit"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[("ANNUALLY", "annually"), ("MONTHLY", "monthly")],
                        max_length=8,
                    ),
                ),
                ("amount", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionnaire.householdadult",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="welfarebenefit",
            constraint=models.UniqueConstraint(
                fields=("recipient", "benefit_type"),
                name="no_duplicated_benefits_per_recipient",
            ),
        ),
    ]
