# Generated by Django 4.0.1 on 2022-03-07 15:16
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0025_remove_maybe_income_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="welfarebenefit",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WEEKLY", "weekly"),
                    ("ANNUALLY", "annually"),
                    ("MONTHLY", "monthly"),
                ],
                max_length=8,
            ),
        ),
    ]
