# Generated by Django 4.0.1 on 2022-03-08 10:47
from django.db import migrations
from django.db import models


def reclassify_forward(apps, schema_editor):
    # old values -> new
    Answers = apps.get_model("questionnaire", "Answers")

    old_to_new = {
        "RESIDENT_HOUSEHOLDER": "OWNER_OCCUPIER",
        "NON_RESIDENT_HOUSEHOLDER": "LANDLORD",
        "OCCUPANT": "TENANT",
        "FRIEND": "OTHER",
        "PARENT": "OTHER",
        "CHILD": "OTHER",
        "FAMILY": "OTHER",
        "OTHER": "OTHER",
    }

    for bod in Answers.objects.all():
        old = bod.respondent_role
        bod.respondent_role = old_to_new[old] if old else ""
        bod.save()


def reclassify_backward(apps, schema_editor):
    # old values -> new
    Answers = apps.get_model("questionnaire", "Answers")

    new_to_old = {
        "OWNER_OCCUPIER": "RESIDENT_HOUSEHOLDER",
        "TENANT": "OCCUPANT",
        "LANDLORD": "NON_RESIDENT_HOUSEHOLDER",
        "OTHER": "OTHER",
    }

    for bod in Answers.objects.all():
        old = bod.respondent_role
        bod.respondent_role = new_to_old[old] if old else ""
        bod.save()


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0026_add_weekly_benefit_option"),
    ]

    operations = [
        migrations.RunPython(reclassify_forward, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="answers",
            name="respondent_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OWNER", "I am the owner-occupier of the property"),
                    ("TENANT", "I am the tenant"),
                    ("LANDLORD", "I am the landlord of the property"),
                    (
                        "OTHER",
                        "I am filling this out on behalf of the tenant/owner occupier",
                    ),
                ],
                max_length=24,
                verbose_name="Relationship of respondent to property",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="respondent_role_other",
            field=models.CharField(
                blank=True,
                max_length=128,
                verbose_name="Relationship of respondent to occupant",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, reclassify_backward),
    ]
