# Generated by Django 4.0.1 on 2022-03-09 14:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0027_new_respondent_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="incomes_complete",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="This is a full account of household income",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="take_home_lt_30k_confirmation",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Household take home pay after tax, national insurance, energy bills and housing costs is less than £30k",
            ),
        ),
    ]
