# Generated by Django 4.0.1 on 2022-06-17 14:44
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0030_alter_welfarebenefit_frequency"),
        ("questionnaire", "0030_answers_child_benefit_claimant_type_and_more"),
    ]

    operations = []
