# Generated by Django 4.0.1 on 2022-06-29 11:53
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0032_alter_welfarebenefit_frequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="in_conservation_area",
        ),
    ]
