# Generated by Django 4.0.1 on 2022-07-04 12:08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0033_remove_answers_in_conservation_area"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answers",
            old_name="trvs_present",
            new_name="trvs_present_old",
        ),
        migrations.RenameField(
            model_name="answers",
            old_name="trvs_present_orig",
            new_name="trvs_present_orig_old",
        ),
    ]
