# Generated by Django 4.0.1 on 2022-07-04 12:08
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0034_rename_trvs_present_answers_trvs_present_old_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="trvs_present",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                verbose_name="Property has themostatic radiator valves",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="trvs_present_orig",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                verbose_name="Property has thermostatic radiator valves according to property data before correction",
            ),
        ),
    ]
