# Generated by Django 4.0.1 on 2022-07-21 10:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0036_data_migration_trvs_present"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="other_heating_fuel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OIL", "Oil"),
                    ("LPG", "LPG (Liquified Petroleum Gas)"),
                    ("COAL", "Coal"),
                    ("WOOD", "Wood"),
                    ("ELECTRIC", "Electricity"),
                    ("DISTRICT", "Via a shared or district heating network"),
                ],
                max_length=11,
                verbose_name="Non-gas central heating fuel used in property",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="other_heating_fuel_orig",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OIL", "Oil"),
                    ("LPG", "LPG (Liquified Petroleum Gas)"),
                    ("COAL", "Coal"),
                    ("WOOD", "Wood"),
                    ("ELECTRIC", "Electricity"),
                    ("DISTRICT", "Via a shared or district heating network"),
                ],
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="property_ownership",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OWNED", "The property is in private ownership"),
                    ("RENTAL", "The property is rented from a private landlord"),
                    (
                        "SOCIAL",
                        "The property is rented from a social landlord (eg. a housing association) or local authority",
                    ),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="respondent_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OWNER", "I am the owner and live in the property"),
                    ("TENANT", "I am a tenant"),
                    ("LANDLORD", "I am the landlord of the property and rent it out"),
                    ("OTHER", "I am filling this out on behalf of the tenant or owner"),
                ],
                max_length=24,
                verbose_name="Relationship of respondent to property",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="state_of_repair",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "EXCELLENT",
                        "Excellent – recently renovated and the walls, roofs, windows, doors and ventilation (for example fans) are in good condition.",
                    ),
                    (
                        "GOOD",
                        "Good – there are no issues with the house and I have ventilation in the kitchen and bathrooms.",
                    ),
                    (
                        "AVERAGE",
                        "Average – there are no issues with the house but I don’t know if I have enough ventilation and I don’t know what condition the external elements (such as roofs, walls and windows) are in.",
                    ),
                    (
                        "POOR",
                        "Poor – There are known issues with the property such as damp or leaks and/or there is no formal ventilation.",
                    ),
                    ("UNKNOWN", "I don't know the state of repair of the property."),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="tolerated_disruption",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "UP_TO_ONE_DAY",
                        "Jobs that take up to three hours inside the property and/or up to one day outside the property",
                    ),
                    (
                        "ONE_TO_FOUR_DAYS",
                        "One or two days of work inside the property and/or three to four days outside the property (for example involving scaffolding etc.)",
                    ),
                    (
                        "THREE_TO_TEN_DAYS",
                        "Up to five days of work inside the property and/or up to ten days outside the property",
                    ),
                    (
                        "TWO_WEEKS_TO_A_MONTH",
                        "Up to two weeks of work inside the property and/or up to one month outside the property",
                    ),
                    ("UNKNOWN", "I don't know."),
                ],
                max_length=20,
                verbose_name="Maximum length of disruption tolerated",
            ),
        ),
    ]
