# Generated by Django 4.0.1 on 2022-07-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0038_alter_answers_property_age_band_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='property_age_band',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('0', 'Before 1900'), ('1900', '1900-1929'), ('1930', '1930-1949'), ('1950', '1950-1966'), ('1967', '1967-1975'), ('1976', '1976-1990'), ('1991', '1991-2002'), ('2003', 'Since 2003'), ('UNKNOWN', "I don't know")], null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='property_age_band_orig',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('0', 'Before 1900'), ('1900', '1900-1929'), ('1930', '1930-1949'), ('1950', '1950-1966'), ('1967', '1967-1975'), ('1976', '1976-1990'), ('1991', '1991-2002'), ('2003', 'Since 2003'), ('UNKNOWN', "I don't know")], null=True, verbose_name='Property age band according to property data source before correction'),
        ),
    ]
