# Generated by Django 4.0.1 on 2022-07-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0040_alter_answers_property_age_band_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='gas_boiler_age',
            field=models.CharField(blank=True, choices=[('BEFORE_2004', 'Before 2004'), ('2004-2014', 'Between 2004 and 2014 (including those years)'), ('2015-2017', 'Between 2015 and 2017 (including those years)'), ('AFTER_2018', 'Since 2018')], max_length=11),
        ),
    ]
