# Generated by Django 4.0.1 on 2022-09-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0041_alter_answers_gas_boiler_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='vulnerable_cariovascular',
            field=models.BooleanField(blank=True, null=True, verbose_name='Anyone in the house is vulnerable due to a cardiovascular condition'),
        ),
    ]
