# Generated by Django 3.2.15 on 2022-09-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0042_alter_answers_vulnerable_cariovascular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='child_benefit_number_elsewhere',
        ),
        migrations.AddField(
            model_name='answers',
            name='child_benefit_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'None'), (1, '1'), (2, '2'), (3, '3'), (4, '4 or more')], null=True, verbose_name='How many children child benefit is claimed for, or for which at least £21.80 per week of maintenance payments are made?'),
        ),
    ]
