# Generated by Django 3.2.15 on 2022-11-04 11:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0043_auto_20220923_1724"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="income_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("YELLOW", "Yellow"),
                    ("GREEN", "Green"),
                ],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="property_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("YELLOW", "Yellow"),
                    ("GREEN", "Green"),
                ],
                max_length=8,
                null=True,
            ),
        ),
    ]
