# Generated by Django 3.2.15 on 2022-11-04 11:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0044_auto_20221104_1126"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="income_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("YELLOW", "Yellow"),
                    ("GREEN", "Green"),
                ],
                max_length=8,
                null=True,
                verbose_name="Income rating (computed field)",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="property_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("AMBER", "Amber"),
                    ("YELLOW", "Yellow"),
                    ("GREEN", "Green"),
                ],
                max_length=8,
                null=True,
                verbose_name="Property rating (computed field)",
            ),
        ),
    ]
