# Generated by Django 3.2.15 on 2023-06-27 11:23
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0045_auto_20221104_1127"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="take_home_lt_30k",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="take_home_lt_30k_confirmation",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="total_income_lt_30k",
        ),
        migrations.AddField(
            model_name="answers",
            name="take_home_lt_31k",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "Yes, it's under that figure"),
                    ("NO", "No, it's over that figure"),
                    ("UNKNOWN", "I don't know"),
                ],
                max_length=7,
                verbose_name="Total household take home pay is under £31,000 pa",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="take_home_lt_31k_confirmation",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Household take home pay after tax, national insurance, energy bills and housing costs is less than £31k",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="total_income_lt_31k",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "Yes, it's under that figure"),
                    ("NO", "No, it's over that figure"),
                    ("UNKNOWN", "I don't know"),
                ],
                max_length=7,
                verbose_name="Total gross household income is under £31,000 pa",
            ),
        ),
    ]
