# Generated by Django 3.2.15 on 2023-07-13 14:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0046_auto_20230627_1223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="uuid",
            field=models.CharField(
                db_index=True, default=None, editable=False, max_length=10, unique=True
            ),
        ),
    ]
