# Generated by Django 3.2.15 on 2023-08-08 09:40
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0047_alter_answers_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
