# Generated by Django 3.2.15 on 2023-08-08 13:54
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0048_alter_answers_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answers",
            old_name="total_income_lt_31k",
            new_name="total_income_lt_30k",
        ),
    ]
