# Generated by Django 3.2.15 on 2023-08-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0049_rename_total_income_lt_31k_answers_total_income_lt_30k'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='ch_timer',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='ch_timer_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='electric_radiators_present',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='electric_radiators_present_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='flat_roof',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='flat_roof_insulated',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='flat_roof_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='gas_boiler_age',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='gas_boiler_broken',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='gas_boiler_present',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='gas_boiler_present_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='has_solar_pv',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='has_solar_pv_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='heat_pump_present',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='heat_pump_present_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='hhrshs_present',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='hhrshs_present_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='hwt_present',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='on_mains_gas',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='on_mains_gas_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='other_heating_fuel',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='other_heating_fuel_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='other_heating_present',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='other_heating_present_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='programmable_thermostat',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='programmable_thermostat_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='property_age_band',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='property_age_band_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='property_form',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='property_form_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='rir_insulated',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='rir_insulated_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='roof_space_insulated',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='roof_space_insulated_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='room_in_roof',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='room_in_roof_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='room_thermostat',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='room_thermostat_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='sap_rating',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='selected_epc',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='smart_thermostat',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='storage_heaters_present',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='storage_heaters_present_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='suspended_floor',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='suspended_floor_insulated',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='suspended_floor_insulated_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='suspended_floor_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='trvs_present',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='trvs_present_old',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='trvs_present_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='trvs_present_orig_old',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='unheated_loft',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='unheated_loft_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='wall_type',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='wall_type_orig',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='walls_insulated',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='walls_insulated_orig',
        ),
        migrations.AddField(
            model_name='answers',
            name='boiler_efficiency',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], max_length=1),
        ),
        migrations.AddField(
            model_name='answers',
            name='boiler_efficiency_orig',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], max_length=1),
        ),
        migrations.AddField(
            model_name='answers',
            name='controls_adequacy',
            field=models.CharField(blank=True, choices=[('Optimal', 'Optimal'), ('SubOptimal', 'Sub Optimal'), ('TopSpec', 'Top Spec')], max_length=10),
        ),
        migrations.AddField(
            model_name='answers',
            name='controls_adequacy_orig',
            field=models.CharField(blank=True, choices=[('Optimal', 'Optimal'), ('SubOptimal', 'Sub Optimal'), ('TopSpec', 'Top Spec')], max_length=10),
        ),
        migrations.AddField(
            model_name='answers',
            name='floor_construction',
            field=models.CharField(blank=True, choices=[('Solid', 'Solid'), ('SuspendedNotTimber', 'Suspended Not Timber'), ('SuspendedTimber', 'Suspended Timber'), ('Unknown', 'Unknown')], max_length=18),
        ),
        migrations.AddField(
            model_name='answers',
            name='floor_construction_orig',
            field=models.CharField(blank=True, choices=[('Solid', 'Solid'), ('SuspendedNotTimber', 'Suspended Not Timber'), ('SuspendedTimber', 'Suspended Timber'), ('Unknown', 'Unknown')], max_length=18),
        ),
        migrations.AddField(
            model_name='answers',
            name='floor_insulation',
            field=models.CharField(blank=True, choices=[('AsBuilt', 'As Built'), ('RetroFitted', 'Retro Fitted'), ('Unknown', 'Unknown')], max_length=11),
        ),
        migrations.AddField(
            model_name='answers',
            name='floor_insulation_orig',
            field=models.CharField(blank=True, choices=[('AsBuilt', 'As Built'), ('RetroFitted', 'Retro Fitted'), ('Unknown', 'Unknown')], max_length=11),
        ),
        migrations.AddField(
            model_name='answers',
            name='glazing',
            field=models.CharField(blank=True, choices=[('Double2002orLater', 'Double 2002 or later'), ('DoubleBefore2002', 'Double before 2002'), ('DoubleButAgeUnknown', 'Double but age unknown'), ('NotDefined', 'Not Defined'), ('Secondary', 'Secondary'), ('Single', 'Single'), ('Triple', 'Triple')], max_length=19),
        ),
        migrations.AddField(
            model_name='answers',
            name='glazing_orig',
            field=models.CharField(blank=True, choices=[('Double2002orLater', 'Double 2002 or later'), ('DoubleBefore2002', 'Double before 2002'), ('DoubleButAgeUnknown', 'Double but age unknown'), ('NotDefined', 'Not Defined'), ('Secondary', 'Secondary'), ('Single', 'Single'), ('Triple', 'Triple')], max_length=19),
        ),
        migrations.AddField(
            model_name='answers',
            name='heated_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='heated_rooms_orig',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='heating',
            field=models.CharField(blank=True, choices=[('Boilers', 'Boilers'), ('Community', 'Community'), ('Electric underfloor', 'Electric Under Floor'), ('Heat pumps (warm air)', 'Heat Pumps (Warm Air)'), ('Heat pumps (wet)', 'Heat Pumps (Wet)'), ('Other systems', 'Other Systems'), ('Room heaters', 'Room Heaters'), ('Storage heaters', 'Storage Heaters'), ('Warm Air (not heat pump)', 'Warm Air (Not Heat Pump)')], max_length=24),
        ),
        migrations.AddField(
            model_name='answers',
            name='heating_orig',
            field=models.CharField(blank=True, choices=[('Boilers', 'Boilers'), ('Community', 'Community'), ('Electric underfloor', 'Electric Under Floor'), ('Heat pumps (warm air)', 'Heat Pumps (Warm Air)'), ('Heat pumps (wet)', 'Heat Pumps (Wet)'), ('Other systems', 'Other Systems'), ('Room heaters', 'Room Heaters'), ('Storage heaters', 'Storage Heaters'), ('Warm Air (not heat pump)', 'Warm Air (Not Heat Pump)')], max_length=24),
        ),
        migrations.AddField(
            model_name='answers',
            name='lodged_epc_band',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='lodged_epc_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='lower_super_output_area_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='answers',
            name='main_fuel',
            field=models.CharField(blank=True, choices=[('Anthracite', 'Anthracite'), ('BulkWoodPellets', 'Bulk Wood Pellets'), ('DualFuelMineralWood', 'Dual Fuel Mineral Wood'), ('ElectricityCommunity', 'Electricity Community'), ('ElectricityNotCommunity', 'Electricity Not Community'), ('GasBottledLPG', 'Gas Bottled LPG'), ('HouseCoalNotCommunity', 'House Coal Not Community'), ('LPGCommunity', 'LPG Community'), ('LPGNotCommunity', 'LPG Not Community'), ('LPGSpecialCondition', 'LPG Special Condition'), ('MainsGasCommunity', 'Mains Gas Community'), ('MainsGasNotCommunity', 'Mains Gas Not Community'), ('OilCommunity', 'Oil Community'), ('OilNotCommunity', 'Oil Not Community'), ('SmokelessCoal', 'Smokeless Coal'), ('WoodChips', 'Wood Chips'), ('WoodLogs', 'Wood Logs')], max_length=23),
        ),
        migrations.AddField(
            model_name='answers',
            name='main_fuel_orig',
            field=models.CharField(blank=True, choices=[('Anthracite', 'Anthracite'), ('BulkWoodPellets', 'Bulk Wood Pellets'), ('DualFuelMineralWood', 'Dual Fuel Mineral Wood'), ('ElectricityCommunity', 'Electricity Community'), ('ElectricityNotCommunity', 'Electricity Not Community'), ('GasBottledLPG', 'Gas Bottled LPG'), ('HouseCoalNotCommunity', 'House Coal Not Community'), ('LPGCommunity', 'LPG Community'), ('LPGNotCommunity', 'LPG Not Community'), ('LPGSpecialCondition', 'LPG Special Condition'), ('MainsGasCommunity', 'Mains Gas Community'), ('MainsGasNotCommunity', 'Mains Gas Not Community'), ('OilCommunity', 'Oil Community'), ('OilNotCommunity', 'Oil Not Community'), ('SmokelessCoal', 'Smokeless Coal'), ('WoodChips', 'Wood Chips'), ('WoodLogs', 'Wood Logs')], max_length=23),
        ),
        migrations.AddField(
            model_name='answers',
            name='property_attachment',
            field=models.CharField(blank=True, choices=[('DETACHED', 'Detached'), ('SEMI_DETACHED', 'Semi-detached'), ('MID_TERRACE', 'Mid-terrace'), ('END_TERRACE', 'End-terrace'), ('ENCLOSED_END_TERRACE', 'Enclosed-end-terrace'), ('ENCLOSED_MID_TERRACE', 'Enclosed-mid-terrace')], max_length=20),
        ),
        migrations.AddField(
            model_name='answers',
            name='property_attachment_orig',
            field=models.CharField(blank=True, choices=[('DETACHED', 'Detached'), ('SEMI_DETACHED', 'Semi-detached'), ('MID_TERRACE', 'Mid-terrace'), ('END_TERRACE', 'End-terrace'), ('ENCLOSED_END_TERRACE', 'Enclosed-end-terrace'), ('ENCLOSED_MID_TERRACE', 'Enclosed-mid-terrace')], max_length=20, verbose_name='Property form according to property data source before correction'),
        ),
        migrations.AddField(
            model_name='answers',
            name='property_construction_years',
            field=models.CharField(blank=True, choices=[('1900', '1900-1929'), ('1930', '1930-1949'), ('1950', '1950-1966'), ('1967', '1967-1975'), ('1976', '1976-1982'), ('1983', '1983-1990'), ('1991', '1991-1995'), ('1996', '1996-2002'), ('2003', '2003-2006'), ('2007', '2007-2011'), ('2012', '2012 onwards'), ('0', 'Before 1900')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='property_construction_years_orig',
            field=models.CharField(blank=True, choices=[('1900', '1900-1929'), ('1930', '1930-1949'), ('1950', '1950-1966'), ('1967', '1967-1975'), ('1976', '1976-1982'), ('1983', '1983-1990'), ('1991', '1991-1995'), ('1996', '1996-2002'), ('2003', '2003-2006'), ('2007', '2007-2011'), ('2012', '2012 onwards'), ('0', 'Before 1900')], max_length=10, null=True, verbose_name='Property age band according to property data source before correction'),
        ),
        migrations.AddField(
            model_name='answers',
            name='realistic_fuel_bill',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='realistic_fuel_bill_orig',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='respondent_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='roof_construction',
            field=models.CharField(blank=True, choices=[('AnotherDwellingAbove', 'Another Dwelling Above'), ('Flat', 'Flat'), ('PitchedNormalLoftAccess', 'Pitched Normal Loft Access'), ('PitchedNormalNoLoftAccess', 'Pitched Normal No Loft Access'), ('PitchedThatched', 'Pitched Thatched'), ('PitchedWithSlopingCeiling', 'Pitched With Sloping Ceiling')], max_length=25),
        ),
        migrations.AddField(
            model_name='answers',
            name='roof_construction_orig',
            field=models.CharField(blank=True, choices=[('AnotherDwellingAbove', 'Another Dwelling Above'), ('Flat', 'Flat'), ('PitchedNormalLoftAccess', 'Pitched Normal Loft Access'), ('PitchedNormalNoLoftAccess', 'Pitched Normal No Loft Access'), ('PitchedThatched', 'Pitched Thatched'), ('PitchedWithSlopingCeiling', 'Pitched With Sloping Ceiling')], max_length=25),
        ),
        migrations.AddField(
            model_name='answers',
            name='roof_insulation',
            field=models.CharField(blank=True, choices=[('AnotherDwellingAbove', 'Another Dwelling Above'), ('AsBuilt', 'As Build'), ('mm100', '100 mm'), ('mm12', '12 mm'), ('mm150', '150 mm'), ('mm200', '200 mm'), ('mm25', '25 mm'), ('mm250', '250 mm'), ('mm270', '270 mm'), ('mm300', '300 mm'), ('mm350', '350 mm'), ('mm400', '400 mm'), ('mm50', '50 mm'), ('mm75', '75 mm'), ('None', 'None'), ('Unknown', 'Unknown')], max_length=20),
        ),
        migrations.AddField(
            model_name='answers',
            name='roof_insulation_orig',
            field=models.CharField(blank=True, choices=[('AnotherDwellingAbove', 'Another Dwelling Above'), ('AsBuilt', 'As Build'), ('mm100', '100 mm'), ('mm12', '12 mm'), ('mm150', '150 mm'), ('mm200', '200 mm'), ('mm25', '25 mm'), ('mm250', '250 mm'), ('mm270', '270 mm'), ('mm300', '300 mm'), ('mm350', '350 mm'), ('mm400', '400 mm'), ('mm50', '50 mm'), ('mm75', '75 mm'), ('None', 'None'), ('Unknown', 'Unknown')], max_length=20),
        ),
        migrations.AddField(
            model_name='answers',
            name='sap_band',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='sap_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='short_uid',
            field=models.CharField(db_index=True, default=None, editable=False, max_length=10, unique=True, verbose_name="Client's unique reference number to be passed in email for reference purpose"),
        ),
        migrations.AddField(
            model_name='answers',
            name='tCO2_current',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='tCO2_current_orig',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='user_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='wall_construction',
            field=models.CharField(blank=True, choices=[('CAVITY', 'Cavity'), ('COB', 'Cob'), ('GRANITE', 'Granite'), ('PARK_HOME', 'Park Home'), ('SANDSTONE', 'Sandstone'), ('SOLID_BRICK', 'Solid Brick'), ('SYSTEM', 'System'), ('TIMBER_FRAME', 'Timber Frame')], max_length=12),
        ),
        migrations.AddField(
            model_name='answers',
            name='wall_construction_orig',
            field=models.CharField(blank=True, choices=[('CAVITY', 'Cavity'), ('COB', 'Cob'), ('GRANITE', 'Granite'), ('PARK_HOME', 'Park Home'), ('SANDSTONE', 'Sandstone'), ('SOLID_BRICK', 'Solid Brick'), ('SYSTEM', 'System'), ('TIMBER_FRAME', 'Timber Frame')], max_length=12, verbose_name='Wall type according to property data source before correction'),
        ),
        migrations.AddField(
            model_name='answers',
            name='walls_insulation',
            field=models.CharField(blank=True, choices=[('AsBuilt', 'As Built'), ('External', 'External'), ('FilledCavity', 'Filled Cavity'), ('FilledCavityPlusExternal', 'Filled Cavity Plus External'), ('FilledCavityPlusInternal', 'Filled Cavity Plus Internal'), ('Internal', 'Internal')], max_length=24),
        ),
        migrations.AddField(
            model_name='answers',
            name='walls_insulation_orig',
            field=models.CharField(blank=True, choices=[('AsBuilt', 'As Built'), ('External', 'External'), ('FilledCavity', 'Filled Cavity'), ('FilledCavityPlusExternal', 'Filled Cavity Plus External'), ('FilledCavityPlusInternal', 'Filled Cavity Plus Internal'), ('Internal', 'Internal')], max_length=24),
        ),
        migrations.AlterField(
            model_name='answers',
            name='property_type',
            field=models.CharField(blank=True, choices=[('FLAT', 'Flat'), ('HOUSE', 'House'), ('BUNGALOW', 'Bungalow'), ('PARK_HOME', 'Park Home'), ('MAISONNETTE', 'Maisonette')], max_length=11),
        ),
        migrations.AlterField(
            model_name='answers',
            name='property_type_orig',
            field=models.CharField(blank=True, choices=[('FLAT', 'Flat'), ('HOUSE', 'House'), ('BUNGALOW', 'Bungalow'), ('PARK_HOME', 'Park Home'), ('MAISONNETTE', 'Maisonette')], max_length=11, verbose_name='Property type according to property data source before correction'),
        ),
    ]
