# Generated by Django 3.2.15 on 2023-08-22 11:22
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0050_auto_20230822_1215"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="user_comment",
        ),
    ]
