# Generated by Django 3.2.15 on 2023-08-22 15:57
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0051_remove_answers_user_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answers",
            old_name="total_income_lt_30k",
            new_name="total_income",
        ),
    ]
