# Generated by Django 3.2.15 on 2023-08-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0052_rename_total_income_lt_30k_answers_total_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='take_home_lt_31k',
            new_name='take_home',
        ),
    ]
