# Generated by Django 3.2.15 on 2023-08-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0053_rename_take_home_lt_31k_answers_take_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='property_attachment',
            field=models.CharField(blank=True, choices=[('Detached', 'Detached'), ('SemiDetached', 'Semi detached'), ('MidTerrace', 'Mid terrace'), ('EndTerrace', 'End terrace'), ('EnclosedEndTerrace', 'Enclosed end terrace'), ('EnclosedMidTerrace', 'Enclosed mid terrace')], max_length=20),
        ),
        migrations.AlterField(
            model_name='answers',
            name='property_attachment_orig',
            field=models.CharField(blank=True, choices=[('Detached', 'Detached'), ('SemiDetached', 'Semi detached'), ('MidTerrace', 'Mid terrace'), ('EndTerrace', 'End terrace'), ('EnclosedEndTerrace', 'Enclosed end terrace'), ('EnclosedMidTerrace', 'Enclosed mid terrace')], max_length=20, verbose_name='Property form according to property data source before correction'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Flat', 'Flat'), ('House', 'House'), ('Bungalow', 'Bungalow'), ('ParkHome', 'Park home'), ('Maisonette', 'Maisonette')], max_length=11),
        ),
        migrations.AlterField(
            model_name='answers',
            name='property_type_orig',
            field=models.CharField(blank=True, choices=[('Flat', 'Flat'), ('House', 'House'), ('Bungalow', 'Bungalow'), ('ParkHome', 'Park home'), ('Maisonette', 'Maisonette')], max_length=11, verbose_name='Property type according to property data source before correction'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='wall_construction',
            field=models.CharField(blank=True, choices=[('CAVITY', 'Cavity'), ('COB', 'Cob'), ('GRANITE', 'Granite'), ('PARK_HOME', 'Park Home'), ('SANDSTONE', 'Sandstone'), ('SOLID_BRICK', 'Solid brick'), ('SYSTEM', 'System'), ('TIMBER_FRAME', 'Timber frame')], max_length=12),
        ),
        migrations.AlterField(
            model_name='answers',
            name='wall_construction_orig',
            field=models.CharField(blank=True, choices=[('CAVITY', 'Cavity'), ('COB', 'Cob'), ('GRANITE', 'Granite'), ('PARK_HOME', 'Park Home'), ('SANDSTONE', 'Sandstone'), ('SOLID_BRICK', 'Solid brick'), ('SYSTEM', 'System'), ('TIMBER_FRAME', 'Timber frame')], max_length=12, verbose_name='Wall type according to property data source before correction'),
        ),
    ]
