# Generated by Django 3.2.15 on 2023-08-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0054_auto_20230823_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='property_construction_years',
            field=models.CharField(blank=True, choices=[('0', 'Before 1900'), ('1900', '1900-1929'), ('1930', '1930-1949'), ('1950', '1950-1966'), ('1967', '1967-1975'), ('1976', '1976-1982'), ('1983', '1983-1990'), ('1991', '1991-1995'), ('1996', '1996-2002'), ('2003', '2003-2006'), ('2007', '2007-2011'), ('2012', '2012 onwards')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='property_construction_years_orig',
            field=models.CharField(blank=True, choices=[('0', 'Before 1900'), ('1900', '1900-1929'), ('1930', '1930-1949'), ('1950', '1950-1966'), ('1967', '1967-1975'), ('1976', '1976-1982'), ('1983', '1983-1990'), ('1991', '1991-1995'), ('1996', '1996-2002'), ('2003', '2003-2006'), ('2007', '2007-2011'), ('2012', '2012 onwards')], max_length=10, null=True, verbose_name='Property age band according to property data source before correction'),
        ),
    ]
