# Generated by Django 3.2.15 on 2023-09-06 11:16
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0055_auto_20230825_1428"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answers",
            old_name="tCO2_current",
            new_name="t_co2_current",
        ),
        migrations.RenameField(
            model_name="answers",
            old_name="tCO2_current_orig",
            new_name="t_co2_current_orig",
        ),
    ]
