# Generated by Django 3.2.15 on 2023-09-08 18:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0057_auto_20230908_1901"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="uprn",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
