# Generated by Django 3.2.15 on 2023-09-11 17:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0059_auto_20230909_1526"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="property_ownership",
        ),
        migrations.AddField(
            model_name="answers",
            name="tenure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OwnerOccupied", "The property is occupied by its owner"),
                    ("RentedPrivate", "The property is rented from a private landlord"),
                    (
                        "RentedSocial",
                        "The property is rented from a social landlord (eg. a housing association) or local authority",
                    ),
                    ("Unknown", "Unknown"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="controls_adequacy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Optimal", "Optimal"),
                    ("Sub Optimal", "Sub optimal"),
                    ("Top Spec", "Top spec"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="controls_adequacy_orig",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Optimal", "Optimal"),
                    ("Sub Optimal", "Sub optimal"),
                    ("Top Spec", "Top spec"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="glazing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Double 2002 or later", "Double 2002 or later"),
                    ("Double before 2002", "Double before 2002"),
                    ("Double but age unknown", "Double but age unknown"),
                    ("NotDefined", "Not Defined"),
                    ("Secondary", "Secondary"),
                    ("Single", "Single"),
                    ("Triple", "Triple"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="glazing_orig",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Double 2002 or later", "Double 2002 or later"),
                    ("Double before 2002", "Double before 2002"),
                    ("Double but age unknown", "Double but age unknown"),
                    ("NotDefined", "Not Defined"),
                    ("Secondary", "Secondary"),
                    ("Single", "Single"),
                    ("Triple", "Triple"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="property_construction_years",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Before 1900", "Before 1900"),
                    ("1900-1929", "1900-1929"),
                    ("1930-1949", "1930-1949"),
                    ("1950-1966", "1950-1966"),
                    ("1967-1975", "1967-1975"),
                    ("1976-1982", "1976-1982"),
                    ("1983-1990", "1983-1990"),
                    ("1991-1995", "1991-1995"),
                    ("1996-2002", "1996-2002"),
                    ("2003-2006", "2003-2006"),
                    ("2007-2011", "2007-2011"),
                    ("2012 onwards", "2012 onwards"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="property_construction_years_orig",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Before 1900", "Before 1900"),
                    ("1900-1929", "1900-1929"),
                    ("1930-1949", "1930-1949"),
                    ("1950-1966", "1950-1966"),
                    ("1967-1975", "1967-1975"),
                    ("1976-1982", "1976-1982"),
                    ("1983-1990", "1983-1990"),
                    ("1991-1995", "1991-1995"),
                    ("1996-2002", "1996-2002"),
                    ("2003-2006", "2003-2006"),
                    ("2007-2011", "2007-2011"),
                    ("2012 onwards", "2012 onwards"),
                ],
                max_length=12,
                null=True,
                verbose_name="Property age band according to property data source before correction",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="roof_insulation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Another Dwelling Above", "Another dwelling above"),
                    ("AsBuilt", "As build"),
                    ("mm100", "100 mm"),
                    ("mm12", "12 mm"),
                    ("mm150", "150 mm"),
                    ("mm200", "200 mm"),
                    ("mm25", "25 mm"),
                    ("mm250", "250 mm"),
                    ("mm270", "270 mm"),
                    ("mm300", "300 mm"),
                    ("mm350", "350 mm"),
                    ("mm400", "400 mm"),
                    ("mm50", "50 mm"),
                    ("mm75", "75 mm"),
                    ("None", "None"),
                    ("Unknown", "Unknown"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="roof_insulation_orig",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Another Dwelling Above", "Another dwelling above"),
                    ("AsBuilt", "As build"),
                    ("mm100", "100 mm"),
                    ("mm12", "12 mm"),
                    ("mm150", "150 mm"),
                    ("mm200", "200 mm"),
                    ("mm25", "25 mm"),
                    ("mm250", "250 mm"),
                    ("mm270", "270 mm"),
                    ("mm300", "300 mm"),
                    ("mm350", "350 mm"),
                    ("mm400", "400 mm"),
                    ("mm50", "50 mm"),
                    ("mm75", "75 mm"),
                    ("None", "None"),
                    ("Unknown", "Unknown"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="wall_construction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cavity", "Cavity"),
                    ("Cob", "Cob"),
                    ("Granite", "Granite"),
                    ("Park home", "Park home"),
                    ("Sandstone", "Sandstone"),
                    ("Solid brick", "Solid brick"),
                    ("System", "System"),
                    ("Timber frame", "Timber frame"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="wall_construction_orig",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cavity", "Cavity"),
                    ("Cob", "Cob"),
                    ("Granite", "Granite"),
                    ("Park home", "Park home"),
                    ("Sandstone", "Sandstone"),
                    ("Solid brick", "Solid brick"),
                    ("System", "System"),
                    ("Timber frame", "Timber frame"),
                ],
                max_length=128,
                verbose_name="Wall type according to property data source before correction",
            ),
        ),
    ]
