# Generated by Django 3.2.15 on 2023-09-12 13:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0060_auto_20230911_1828"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="boiler_efficiency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="boiler_efficiency_orig",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="lodged_epc_band",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="sap_band",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="tenure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OwnerOccupied", "The property is occupied by its owner"),
                    ("RentedPrivate", "The property is rented from a private landlord"),
                    (
                        "RentedSocial",
                        "The property is rented from a social landlord or local authority",
                    ),
                    ("Unknown", "Unknown"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="wall_construction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cavity", "Cavity"),
                    ("Cob", "Cob"),
                    ("Granite", "Granite"),
                    ("Park Home", "Park home"),
                    ("Sandstone", "Sandstone"),
                    ("Solid Brick", "Solid brick"),
                    ("System", "System"),
                    ("Timber Frame", "Timber frame"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="wall_construction_orig",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cavity", "Cavity"),
                    ("Cob", "Cob"),
                    ("Granite", "Granite"),
                    ("Park Home", "Park home"),
                    ("Sandstone", "Sandstone"),
                    ("Solid Brick", "Solid brick"),
                    ("System", "System"),
                    ("Timber Frame", "Timber frame"),
                ],
                max_length=128,
                verbose_name="Wall type according to property data source before correction",
            ),
        ),
    ]
