# Generated by Django 3.2.15 on 2023-09-25 13:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0061_auto_20230912_1431"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="boiler_efficiency_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="consented_callback",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="consented_future_schemes",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="contribution_capacity",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="controls_adequacy_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="floor_construction_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="floor_insulation_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="glazing_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="heated_rooms_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="heating_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="main_fuel_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="motivation_better_comfort",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="motivation_environment",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="motivation_lower_bills",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="motivation_unknown",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="property_attachment_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="property_construction_years_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="property_type_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="realistic_fuel_bill_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="roof_construction_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="roof_insulation_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="state_of_repair",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="t_co2_current_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="tolerated_disruption",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="wall_construction_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="walls_insulation_orig",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="will_correct_floor",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="will_correct_heating",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="will_correct_roof",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="will_correct_type",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="will_correct_walls",
        ),
        migrations.AlterField(
            model_name="answers",
            name="floor_construction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Solid", "Solid"),
                    ("SuspendedNotTimber", "Suspended - not timber"),
                    ("SuspendedTimber", "Suspended - timber"),
                    ("Unknown", "Unknown"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="floor_insulation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AsBuilt", "As built"),
                    ("RetroFitted", "Retrofitted"),
                    ("Unknown", "Unknown"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="main_fuel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Anthracite", "Anthracite"),
                    ("BulkWoodPellets", "Bulk wood pellets"),
                    ("DualFuelMineralWood", "Dual fuel mineral wood"),
                    ("ElectricityCommunity", "Electricity - community"),
                    ("ElectricityNotCommunity", "Electricity - not community"),
                    ("GasBottledLPG", "Bottled gas (LPG)"),
                    ("HouseCoalNotCommunity", "Coal - not community"),
                    ("LPGCommunity", "LPG - community"),
                    ("LPGNotCommunity", "LPG - not community"),
                    ("LPGSpecialCondition", "LPG - special condition"),
                    ("MainsGasCommunity", "Mains gas - community"),
                    ("MainsGasNotCommunity", "Mains gas - not community"),
                    ("OilCommunity", "Oil - community"),
                    ("OilNotCommunity", "Oil - not community"),
                    ("SmokelessCoal", "Smokeless coal"),
                    ("WoodChips", "Wood chips"),
                    ("WoodLogs", "Wood logs"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="roof_construction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AnotherDwellingAbove", "Another dwelling above"),
                    ("Flat", "Flat"),
                    ("PitchedNormalLoftAccess", "Pitched - loft access"),
                    ("PitchedNormalNoLoftAccess", "Pitched - no loft access"),
                    ("PitchedThatched", "Pitched thatched"),
                    ("PitchedWithSlopingCeiling", "Pitched with sloping ceiling"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="roof_insulation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Another Dwelling Above", "Another dwelling above"),
                    ("AsBuilt", "As built"),
                    ("mm100", "100 mm"),
                    ("mm12", "12 mm"),
                    ("mm150", "150 mm"),
                    ("mm200", "200 mm"),
                    ("mm25", "25 mm"),
                    ("mm250", "250 mm"),
                    ("mm270", "270 mm"),
                    ("mm300", "300 mm"),
                    ("mm350", "350 mm"),
                    ("mm400", "400 mm"),
                    ("mm50", "50 mm"),
                    ("mm75", "75 mm"),
                    ("None", "None"),
                    ("Unknown", "Unknown"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="tenure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OwnerOccupied", "The property is occupied by its owner"),
                    ("RentedPrivate", "Rented - private"),
                    ("RentedSocial", "Rented - social"),
                    ("Unknown", "Unknown"),
                ],
                max_length=128,
                verbose_name="Property ownership",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="walls_insulation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AsBuilt", "As built"),
                    ("External", "External wall insulation"),
                    ("FilledCavity", "Filled cavity"),
                    (
                        "FilledCavityPlusExternal",
                        "Filled cavity plus external wall insulation",
                    ),
                    (
                        "FilledCavityPlusInternal",
                        "Filled cavity plus internal wall insulation",
                    ),
                    ("Internal", "Internal wall insulation"),
                ],
                max_length=128,
            ),
        ),
    ]
