# Generated by Django 3.2.15 on 2023-10-20 10:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0063_auto_20231016_1945"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="source_of_info_about_pec",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Door knocking", "Door knocking"),
                    ("Facebook", "Facebook"),
                    ("Flyer/poster", "Flyer or poster"),
                    ("Instagram", "Instagram"),
                    ("Letter in the post", "Letter in the post"),
                    ("LinkedIn", "LinkedIn"),
                    ("Print media", "Newspaper or magazine"),
                    ("Prior relationship with PEC", "Prior relationship with PEC"),
                    ("Radio", "Radio"),
                    (
                        "Signpost - Community organisation",
                        "Referred by community organisation",
                    ),
                    ("Signpost - Charity", "Referred by charity"),
                    ("Signpost - Council", "Referred by council"),
                    ("Signpost - Local business", "Referred by local business"),
                    ("Twitter", "X, formerly known as Twitter"),
                    ("Web search", "Web search"),
                    ("Word of mouth", "Word of mouth"),
                    ("Not Yet Specified", "Other"),
                    ("Input label", "Please choose option"),
                ],
                default="Input label",
                max_length=128,
            ),
        ),
    ]
