# Generated by Django 3.2.15 on 2023-10-25 13:54
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0064_alter_answers_source_of_info_about_pec"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HouseholdAdult",
        ),
        migrations.DeleteModel(
            name="WelfareBenefit",
        ),
    ]
