# Generated by Django 3.2.15 on 2023-11-06 14:16
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0065_auto_20231025_1454"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="over_60s",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "None"), (1, "1"), (2, "2"), (3, "3"), (4, "4 or more")],
                null=True,
                verbose_name="Number of seniors (over 60 years old) living in the property",
            ),
        ),
    ]
