# Generated by Django 3.2.15 on 2023-11-13 16:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0065_auto_20231025_1454"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="council_tax_reduction",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Is the household entitled to a Council Tax reduction",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="housing_costs",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Housing costs"
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="seniors",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "None"), (1, "1"), (2, "2"), (3, "3"), (4, "4 or more")],
                null=True,
                verbose_name="Number of seniors (over 60 years old) living in the property",
            ),
        ),
    ]
