# Generated by Django 3.2.15 on 2023-11-06 15:49
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0066_answers_over_60s"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="housing_costs",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Housing costs"
            ),
        ),
    ]
