# Generated by Django 3.2.15 on 2023-11-13 19:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0066_auto_20231113_1639"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="vulnerable_child_pregnancy",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="vulnerable_cns",
        ),
        migrations.AddField(
            model_name="answers",
            name="vulnerable_children",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Anyone in the house is with young children (from new-born to school age)",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="vulnerable_pregnancy",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Anyone in the house is pregnant"
            ),
        ),
    ]
