# Generated by Django 3.2.15 on 2023-11-08 13:58
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0066_answers_over_60s"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answers",
            old_name="over_60s",
            new_name="seniors",
        ),
    ]
