# Generated by Django 3.2.15 on 2023-11-15 21:30
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0067_auto_20231113_1957"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="vulnerabilities_general",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Anyone in the house is vulnerable"
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="vulnerable_comments",
            field=models.CharField(
                blank=True,
                max_length=400,
                null=True,
                verbose_name="User's input on other vulnerabilities",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="vulnerable_immunosuppression",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Anyone in the house is vulnerable due to immunosuppression",
            ),
        ),
    ]
