# Generated by Django 3.2.15 on 2023-11-09 14:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0067_rename_over_60s_answers_seniors"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="council_tax_reduction",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Is the household entitled to a Council Tax reduction",
            ),
        ),
    ]
