# Generated by Django 3.2.15 on 2023-11-16 14:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0068_auto_20231115_2130"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="means_tested_benefits",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Respondent receives means tested benefits",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="past_means_tested_benefits",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Respondent received means tested benefits in the past 18 months",
            ),
        ),
    ]
