# Generated by Django 3.2.15 on 2023-11-16 18:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0069_auto_20231116_1447"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="incomes_complete",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="take_home",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="take_home_lt_31k_confirmation",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="total_income",
        ),
        migrations.AddField(
            model_name="answers",
            name="household_income",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Total gross household income before tax",
            ),
        ),
    ]
