# Generated by Django 3.2.15 on 2023-11-17 10:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0070_auto_20231116_1846"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="child_benefit_eligibility_complete",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="child_benefit_threshold",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="income_lt_child_benefit_threshold",
        ),
        migrations.AddField(
            model_name="answers",
            name="free_school_meals_eligibility",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Children living in household eligible for free school meals",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="child_benefit_claimant_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SINGLE", "Single claimant"),
                    ("JOINT", "Member of a couple"),
                ],
                max_length=10,
                null=True,
                verbose_name="The person receiving child benefit is a single claimant (not member of a couple), or joint claimant.",
            ),
        ),
    ]
