# Generated by Django 3.2.15 on 2023-11-17 12:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0071_auto_20231117_1056"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="nmt4properties",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="No more than 4 properties in landlord's portfolio",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="savings",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Amount of savings"
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="willing_to_contribute",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Landlord be willing to contribute 33% of all spending",
            ),
        ),
    ]
