# Generated by Django 3.2.15 on 2023-11-29 15:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0072_auto_20231117_1212"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="company_name",
            field=models.CharField(
                blank=True,
                max_length=128,
                verbose_name="Landlord company name (if applicable)",
            ),
        ),
    ]
