# Generated by Django 3.2.15 on 2023-12-08 12:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0073_answers_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="multiple_deprivation_index",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
