# Generated by Django 3.2.15 on 2023-12-11 21:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0074_answers_multiple_deprivation_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="adults",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                null=True,
                verbose_name="Number of adults living in the property",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="child_benefit_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5 or more")],
                null=True,
                verbose_name="How many children child benefit is claimed for, or for which at least £21.80 per week of maintenance payments are made?",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="children",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "None"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                null=True,
                verbose_name="Number of children living in the property",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="seniors",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "None"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                null=True,
                verbose_name="Number of seniors (over 60 years old) living in the property",
            ),
        ),
    ]
