# Generated by Django 3.2.15 on 2023-12-12 16:19
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0075_auto_20231211_2152"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="savings",
        ),
    ]
