# Generated by Django 3.2.15 on 2023-12-15 12:02
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0077_auto_20231213_1144"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="income_rating",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="property_rating",
        ),
    ]
