# Generated by Django 3.2.15 on 2023-12-19 17:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0078_auto_20231215_1202"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="free_school_meals_eligibility",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Children living in household eligible for free school meals",
            ),
        ),
    ]
