# Generated by Django 3.2.15 on 2024-01-03 17:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0079_alter_answers_free_school_meals_eligibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="heating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Boilers", "Boilers"),
                    ("Community", "Community"),
                    ("Electric underfloor", "Electric underfloor"),
                    ("Heat pumps (warm air)", "Heat pumps (warm air)"),
                    ("Heat pumps (wet)", "Heat pumps (wet)"),
                    ("Other systems", "Other systems"),
                    ("Room heaters", "Room heaters"),
                    ("Storage heaters", "Storage heaters"),
                    ("Warm Air (not heat pump)", "Warm air (not heat pump)"),
                ],
                max_length=128,
            ),
        ),
    ]
