# Generated by Django 3.2.15 on 2024-01-09 21:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0080_alter_answers_heating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="adults",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                    (6, "Six"),
                    (7, "Seven"),
                    (8, "Eight"),
                    (9, "Nine"),
                    (10, "Ten"),
                ],
                null=True,
                verbose_name="Number of adults living in the property",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="child_benefit_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                ],
                null=True,
                verbose_name="How many children child benefit is claimed for, or for which at least £21.80 per week of maintenance payments are made?",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="children",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "None"),
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                    (6, "Six"),
                    (7, "Seven"),
                    (8, "Eight"),
                    (9, "Nine"),
                    (10, "Ten"),
                ],
                null=True,
                verbose_name="Number of children living in the property",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="seniors",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "None"),
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                    (6, "Six"),
                    (7, "Seven"),
                    (8, "Eight"),
                    (9, "Nine"),
                    (10, "Ten"),
                ],
                null=True,
                verbose_name="Number of seniors (over 60 years old) living in the property",
            ),
        ),
    ]
