# Generated by Django 3.2.15 on 2024-01-23 17:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0082_answers_council_tax_band"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="advice_needed_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
