# Generated by Django 3.2.15 on 2024-02-01 16:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0083_answers_advice_needed_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="parity_object_id",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True
            ),
        ),
    ]
