# Generated by Django 3.2.15 on 2024-12-10 16:43
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0084_answers_parity_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="main_fuel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Anthracite", "Anthracite"),
                    ("BulkWoodPellets", "Bulk wood pellets"),
                    ("DualFuelMineralWood", "Dual Fuel Mineral Wood"),
                    ("ElectricityCommunity", "Electricity - community"),
                    ("ElectricityNotCommunity", "Electricity - not community"),
                    ("GasBottledLPG", "Bottled gas (LPG)"),
                    ("HouseCoalNotCommunity", "Coal - not community"),
                    ("LPGCommunity", "LPG - community"),
                    ("LPGNotCommunity", "LPG - not community"),
                    ("LPGSpecialCondition", "LPG - special condition"),
                    ("MainsGasCommunity", "Mains gas - community"),
                    ("MainsGasNotCommunity", "Mains gas - not community"),
                    ("OilCommunity", "Oil - community"),
                    ("OilNotCommunity", "Oil - not community"),
                    ("SmokelessCoal", "Smokeless coal"),
                    ("WoodChips", "Wood chips"),
                    ("WoodLogs", "Wood logs"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="source_of_info_about_pec",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Door knocking", "Door knocking"),
                    ("Facebook", "Facebook"),
                    ("Flyer/poster", "Flyer or poster"),
                    ("Instagram", "Instagram"),
                    ("Letter in the post", "Letter in the post"),
                    ("LinkedIn", "LinkedIn"),
                    ("Print media", "Newspaper or magazine"),
                    ("Prior relationship with PEC", "Prior relationship with PEC"),
                    ("Radio", "Radio"),
                    (
                        "Signpost - Community organisation",
                        "Referred by community organisation",
                    ),
                    ("Signpost - Charity", "Referred by charity"),
                    ("Signpost - Council", "Referred by council"),
                    ("Signpost - Local business", "Referred by local business"),
                    ("Twitter", "X, formerly known as Twitter"),
                    ("Web search", "Web search"),
                    ("Business card in shop", "Business card in shop"),
                    ("Word of mouth", "Word of mouth"),
                    ("Not Yet Specified", "Other"),
                    ("Input label", "Please choose option"),
                ],
                default="Input label",
                max_length=128,
            ),
        ),
    ]
