# Generated by Django 3.2.15 on 2024-12-18 16:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0085_auto_20241210_1643"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="income_decile",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
