# Generated by Django 3.2.15 on 2025-12-22 21:16
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0088_alter_udprn_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="willing_to_contribute",
        ),
    ]
